# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 21:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20171102_2255'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
