# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 21:55
from __future__ import unicode_literals

from django.db import migrations, models
import images.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('images', '0003_delete_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=20)),
                ('original', models.ImageField(upload_to=images.models.photo_folder)),
                ('thumbnail', models.ImageField(upload_to=images.models.photo_folder)),
            ],
        ),
    ]
