# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 23:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(help_text='Varadero, Vinales, Old Havana', max_length=255)),
                ('description', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prov', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='destination',
            name='prov',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='destination.Province'),
        ),
    ]
