# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 01:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenitie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('title_en', models.CharField(blank=True, max_length=200, null=True)),
                ('title_es', models.CharField(blank=True, max_length=200, null=True)),
                ('title_fr', models.CharField(blank=True, max_length=200, null=True)),
                ('title_de', models.CharField(blank=True, max_length=200, null=True)),
                ('meta_description', models.CharField(blank=True, max_length=200)),
                ('meta_description_en', models.CharField(blank=True, max_length=200, null=True)),
                ('meta_description_es', models.CharField(blank=True, max_length=200, null=True)),
                ('meta_description_fr', models.CharField(blank=True, max_length=200, null=True)),
                ('meta_description_de', models.CharField(blank=True, max_length=200, null=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('name_en', models.CharField(max_length=100, null=True, unique=True)),
                ('name_es', models.CharField(max_length=100, null=True, unique=True)),
                ('name_fr', models.CharField(max_length=100, null=True, unique=True)),
                ('name_de', models.CharField(max_length=100, null=True, unique=True)),
                ('importance', models.PositiveIntegerField()),
                ('max_guest', models.PositiveIntegerField()),
                ('bedrooms', models.PositiveIntegerField()),
                ('beds', models.PositiveIntegerField()),
                ('baths', models.PositiveIntegerField()),
                ('weekly_discount', models.PositiveIntegerField(blank=True, null=True)),
                ('monthly_discount', models.PositiveIntegerField(blank=True, null=True)),
                ('cleaning_fee', models.PositiveIntegerField(blank=True, null=True)),
                ('house_rules', models.TextField()),
                ('main_photo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_main_photo', to='images.Photo')),
                ('photos', models.ManyToManyField(related_name='home_photos', to='images.Photo')),
            ],
            options={
                'verbose_name': 'Home',
                'verbose_name_plural': 'Homes',
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('title_en', models.CharField(blank=True, max_length=200, null=True)),
                ('title_es', models.CharField(blank=True, max_length=200, null=True)),
                ('title_fr', models.CharField(blank=True, max_length=200, null=True)),
                ('title_de', models.CharField(blank=True, max_length=200, null=True)),
                ('meta_description', models.CharField(blank=True, max_length=200)),
                ('meta_description_en', models.CharField(blank=True, max_length=200, null=True)),
                ('meta_description_es', models.CharField(blank=True, max_length=200, null=True)),
                ('meta_description_fr', models.CharField(blank=True, max_length=200, null=True)),
                ('meta_description_de', models.CharField(blank=True, max_length=200, null=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('name_en', models.CharField(max_length=100, null=True, unique=True)),
                ('name_es', models.CharField(max_length=100, null=True, unique=True)),
                ('name_fr', models.CharField(max_length=100, null=True, unique=True)),
                ('name_de', models.CharField(max_length=100, null=True, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('description_en', models.CharField(max_length=255, null=True)),
                ('description_es', models.CharField(max_length=255, null=True)),
                ('description_fr', models.CharField(max_length=255, null=True)),
                ('description_de', models.CharField(max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Lodging',
                'verbose_name_plural': 'Lodgings',
                'abstract': False,
            },
        ),
    ]
