# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0002_auto_20171102_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='description',
            field=models.TextField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='slug',
            field=models.SlugField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotel',
            name='slug',
            field=models.SlugField(default='slug', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hotel',
            name='description',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='description_de',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='description_en',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='description_es',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='description_fr',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
