# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0006_auto_20171103_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('basic', 'Basic'), ('secondary', 'Secondary')], default='basic', max_length=20)),
                ('amenity', models.CharField(max_length=100)),
                ('font_icon', models.CharField(blank=True, max_length=20)),
                ('img_icon', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Amenitie',
        ),
        migrations.AddField(
            model_name='home',
            name='amenities',
            field=models.ManyToManyField(to='lodging.Amenity'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='amenities',
            field=models.ManyToManyField(to='lodging.Amenity'),
        ),
    ]
