# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0008_home_host'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amenity',
            options={'verbose_name': 'Amenity', 'verbose_name_plural': 'Amenities'},
        ),
        migrations.AddField(
            model_name='amenity',
            name='amenity_de',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='amenity',
            name='amenity_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='amenity',
            name='amenity_es',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='amenity',
            name='amenity_fr',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
