# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 23:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0001_initial'),
        ('lodging', '0009_auto_20171103_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='destination.Destination'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='destination.Destination'),
        ),
    ]
