# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 21:38
from __future__ import unicode_literals

from django.db import migrations
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0010_auto_20171103_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='position',
            field=geoposition.fields.GeopositionField(blank=True, max_length=42, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='position',
            field=geoposition.fields.GeopositionField(blank=True, max_length=42, null=True),
        ),
    ]
