# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 21:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0011_auto_20171104_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='main_photo',
        ),
        migrations.RemoveField(
            model_name='home',
            name='photos',
        ),
    ]
