# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 22:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_photo'),
        ('lodging', '0012_auto_20171104_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='main_photo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='images.Photo'),
        ),
        migrations.AddField(
            model_name='home',
            name='photos',
            field=models.ManyToManyField(related_name='home_photos', to='images.Photo'),
        ),
    ]
