# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0013_auto_20171104_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='description_de',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='description_es',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='description_fr',
            field=models.TextField(null=True),
        ),
    ]
