# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 01:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0015_auto_20171104_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='main_photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='images.Photo'),
        ),
    ]
