# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0016_auto_20171106_2015'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='home',
            options={'ordering': ['-importance'], 'verbose_name': 'Home', 'verbose_name_plural': 'Homes'},
        ),
        migrations.AddField(
            model_name='home',
            name='price',
            field=models.PositiveIntegerField(default=75),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='type',
            field=models.CharField(choices=[('entire_room', 'Entire home'), ('shared_room', 'Shared room'), ('private_room', 'Shared room')], default='entire_room', max_length=20),
        ),
        migrations.AddField(
            model_name='hotel',
            name='price',
            field=models.PositiveIntegerField(default=128),
            preserve_default=False,
        ),
    ]
