# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 03:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0017_auto_20171108_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='home',
            name='meta_description_de',
        ),
        migrations.RemoveField(
            model_name='home',
            name='meta_description_en',
        ),
        migrations.RemoveField(
            model_name='home',
            name='meta_description_es',
        ),
        migrations.RemoveField(
            model_name='home',
            name='meta_description_fr',
        ),
        migrations.RemoveField(
            model_name='home',
            name='title',
        ),
        migrations.RemoveField(
            model_name='home',
            name='title_de',
        ),
        migrations.RemoveField(
            model_name='home',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='home',
            name='title_es',
        ),
        migrations.RemoveField(
            model_name='home',
            name='title_fr',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='meta_description_de',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='meta_description_en',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='meta_description_es',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='meta_description_fr',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='title',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='title_de',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='title_es',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='title_fr',
        ),
    ]
