# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0021_auto_20171109_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='house_rules_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='house_rules_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='house_rules_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='house_rules_fr',
            field=models.TextField(null=True),
        ),
    ]
