# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 16:12
from __future__ import unicode_literals

from django.db import migrations
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0022_auto_20171109_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='position',
            field=geoposition.fields.GeopositionField(blank=True, default='23.1135925,-82.36659559999998', max_length=42, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='position',
            field=geoposition.fields.GeopositionField(blank=True, default='23.1135925,-82.36659559999998', max_length=42, null=True),
        ),
    ]
