# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0023_auto_20171110_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='rating',
            field=models.PositiveIntegerField(blank=True, default=4, null=True),
        ),
    ]
